### ISSUE TITLE
Quest hologram text on npc head are missing

### ISSUE THREAD

**Issue by h266579110** [SkytAsul/BeautyQuests#214] opened 2022-03-23 17:15 UTC
**Describe the bug**	
Quest hologram text on npc head are missing after server restarted.
Already check quest yml file its set up.
![image](https://user-images.githubusercontent.com/14806222/159757096-5042b564-51e3-40df-9b90-51f1ef005e44.png)

**Reproduction**
1. Create a quest and specific a npc to acceptable quest.
2. Server restart.
3. hologram text disappear.

**Screenshots, error messages**
No error messages, no holograms text on npc head
![image](https://user-images.githubusercontent.com/14806222/159757041-7f3daad6-8c2b-4102-b622-c023cb4505d0.png)

**Software**
BeautyQuests version: 0.19.2-SNAPSHOT
Game version: 1.18.2
Server version: 1.18.2-267
Server type (e.i. PaperSpigot): Paper
Are you using a protocol hack (like ViaVersion)?
ViaVersion, ViaBackward

**Additional context (optional)**

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment] 2022-03-29 07:45
Please send _exact_ HolographicDisplays and ProtocolLib versions, for me to be able to reproduce the bug.
Use the "/version <pluginname>" command.

**Comment by h266579110** [comment] 2022-04-02 04:40
> Please send _exact_ HolographicDisplays and ProtocolLib versions, for me to be able to reproduce the bug. Use the "/version " command.

> > version ProtocolLib
> [12:40:09 INFO]: ProtocolLib version 4.8.0
> [12:40:09 INFO]: Provides read/write access to the Minecraft protocol.
> [12:40:09 INFO]: Authors: dmulloy2 and comphenix
> > version HolographicDisplays
> [12:40:13 INFO]: HolographicDisplays version 3.0.0-SNAPSHOT-b205
> [12:40:13 INFO]: Author: filoghost

**Comment by SkytAsul** [comment] 2022-04-03 10:04
I am unable to reproduce the bug, with exactly the same plugins version as yours.
May you send your full BeautyQuests folder?

**Comment by h266579110** [comment] 2022-04-03 13:01
> I am unable to reproduce the bug, with exactly the same plugins version as yours. May you send your full BeautyQuests folder?

https://drive.google.com/file/d/13UqZmz3dMSMWAsRzQPSLTepIXZds5d1z/view?usp=sharing

**Comment by SkytAsul** [comment] 2022-04-07 13:11
I am astonished. I literally copy pasted your config on my server and the holograms are displayed 😭 
May I join your server to run some tests?

**Comment by SkytAsul** [comment] 2022-04-08 21:31
Please try with [build 300](https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/300/artifact/target/beautyquests-0.19.2-SNAPSHOT.jar)

**Comment by h266579110** [comment] 2022-04-09 09:41
> Please try with [build 300](https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/300/artifact/target/beautyquests-0.19.2-SNAPSHOT.jar)

Not solve.
But i found problem, if using ItemsAdder with BeautyQuests will cause this problem, maybe some conflict?
BeautyQuests 0.19.2-SNAPSHOT
ItemsAdder 3.1.0c

**Comment by SkytAsul** [comment] 2022-04-09 12:55
So if you run the server without ItemsAdder the holograms work well??

**Comment by h266579110** [comment] 2022-04-09 14:13
> So if you run the server without ItemsAdder the holograms work well??

Yes, tested.

**Comment by LoneDev6** [comment] 2022-04-11 11:56
ItemsAdder doesn't remove holograms of other plugins and it doesn't rename entities

**Comment by h266579110** [comment] 2022-04-12 09:38
If use /quests reload in-game will able to see holograms back.
![image](https://user-images.githubusercontent.com/14806222/162930439-3146c0d8-6e39-4c0a-8ecd-0baeee01268f.png)

**Comment by LoneDev6** [comment] 2022-04-20 09:08
Are you using the latest Citizens?

**Comment by h266579110** [comment] 2022-04-20 10:26
> 

v2.0.29-b2529

**Comment by LoneDev6** [comment] 2022-04-20 10:40
I doubt that would fix the issue.

@SkytAsul ItemsAdder reloads Citizens when ItemsAdder loads its own custom items/mobs, this might be the cause.
You might have to somehow reapply the nametag to the entity I think, what do you think?

**Comment by SkytAsul** [comment] 2022-04-20 21:14
Oof, yes that's certainly the case. I could make a fix for this, however I think it's a bad practice to reload Citizens as a whole. BeautyQuests is probably not the only plugin that breaks and will break due to this.

**Comment by SkytAsul** [comment] 2022-04-21 12:11
There must be a better way. As ItemsAdder is not open-source, I cannot see exactly how you did your compatibility, but I assume you are using traits? If yes, I think looping through all loaded NPCs with your "reskinning" trait and refreshing the custom model would work.

**Comment by LoneDev6** [comment] 2022-04-21 15:34
Thanks, I'll do more tests. Probably the issues I was facing were related to something else.

**Comment by SkytAsul** [comment] 2022-05-01 09:49
[Dev build 305](https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/306/) may fix your issue. Could you please test it?

**Comment by h266579110** [comment] 2022-05-01 18:51
> [Dev build 306](https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/306/) may fix your issue. Could you please test it?

Issue solved with a WARN msg.
```
[02:46:11 INFO]: [ItemsAdder] Reloading Citizens
[02:46:12 WARN]: [BeautyQuests] Citizens has been reloaded whereas it is highly not recommended for plugins compatibilities. Unexpected behaviors may happen.
```

**Comment by SkytAsul** [comment] 2022-05-01 18:59
Perfect! This is now solved.

**Closed by SkytAsul** 2022-05-01 18:59 UTC
Labels: bug, under testing
